# Development profile - optimized for fast iteration

# Inherit from default
_base: "../default.yaml"

# Override for development
log_level: "DEBUG"
device: "cpu"  # Force CPU for reproducibility

# Smaller grid for faster execution
grid_size: 16

# Reduced simulation parameters
simulation_params:
  steps: 100
  log_interval: 5
  checkpoint_interval: 20

# Modified physics parameters for stability
default_params:
  sigma_u: 0.01  # Larger smearing for stability
  chi_max: 8     # Smaller bond dimensions
  max_bond_dim: 16

# More frequent output
output:
  snapshot_interval: 10

# Enable more diagnostics
probes:
  qei_kernel:
    enabled: true
    safety_margin: 0.1  # Larger safety margin
  
  echo_meter:
    enabled: true
    measure_interval: 5  # More frequent measurements