# GPU profile - optimized for high-performance computation

# Inherit from default
_base: "../default.yaml"

# GPU settings
device: "cuda"
log_level: "INFO"

# Larger grids for GPU
grid_size: 64

# Extended simulation parameters
simulation_params:
  steps: 10000
  log_interval: 50
  checkpoint_interval: 500

# GPU-optimized physics parameters
default_params:
  chi_max: 32
  max_bond_dim: 64
  sigma_u: 0.002  # Finer resolution
  
  # Larger capacity for GPU
  cap_max: 128

# Less frequent snapshots to reduce overhead
output:
  snapshot_interval: 200
  format: "parquet"  # More efficient for large datasets

# Optimized probe settings
probes:
  qei_kernel:
    enabled: true
    safety_margin: 0.02  # Tighter margins for precision
  
  echo_meter:
    enabled: true
    measure_interval: 20