# Test configuration for a short simulation run
engine:
  r0: 0.5
  m0: 1.0
  enable_recorder: true

physics:
  d_H: 3.12
  C_RT: 91.64
  kappa: 0.015
  sigma_u: 0.004
  mu0: 1.0
  L_rg: 1.0
  d_boundary: 2

simulation:
  dt: 0.05              # Larger time step for faster test
  r_start: 0.1
  r_end: 0.5            # Much shorter range
  r_step: 0.1           # Larger steps
  max_steps: 5          # Very few steps
  save_interval: 2

output:
  recordings_path: "./test_recordings"
  snapshot_path: "./test_snapshots"